
export let getData= "get_data"
export let editTableData = "edit_table_data"
export let getDataForm1 = "ADD_TODO"
export let login_api    = "Login"
export let empData = "emp_get_data"
export let addEmployees = "Add_employees"
export let EditEmp = "Edit_Employee"
export let DeleteEmp = "delete_employee"
export let ChangeProfilePic = "change_user_profile"